version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/golang:1.13
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t zatsubun/circleci-openjdk-14-buster-plantuml:latest .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push zatsubun/circleci-openjdk-14-buster-plantuml

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
